cmake: modify build system for OpenWrt compatibility
facebook/bpfilter pull request #172
Opened 2024-11-14 09:44 UTC by liudf0716

- Disable testing and documentation builds by default
    - Add conditional inclusion of tests and documentation
    - Handle argp dependency with find_library
    - Make development tools (clang-tidy, clang-format) optional
    - Add flexible bpftool handling with fallback paths
    - Improve build system modularity and configurability

    This modification adjusts the build system to ensure compatibility
    with the OpenWrt environment, making necessary changes for a successful build.

    Signed-off-by: Dengfeng Liu <liudf0716@gmail.com>

2024-11-25 14:21 UTC, qdeslandes commented on CMakeLists.txt
> +option(BUILD_DOCS "Enable building documentation" OFF)
Those should be enabled by default to keep the current behaviour. Use `WITH_XXX` instead of `BUILD_XXX` similarly to #174.

2024-11-25 14:21 UTC, qdeslandes commented on CMakeLists.txt
> +    find_package(Doxygen REQUIRED)
Move this in `docs/CMakeLists.txt`, and modify `add_subdirectory(docs)` below to:

```cmake
if (WITH_DOCS)
    add_subdirectory(docs)
endif ()
```

2024-11-25 14:21 UTC, qdeslandes commented on CMakeLists.txt
> +endif()
Same

2024-11-25 14:21 UTC, qdeslandes commented on CMakeLists.txt
> +    PATHS ${CMAKE_SYSROOT}/usr/lib
[According to CMake's doc](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSROOT.html), search path are automatically prefixed with `CMAKE_SYSROOT`, so there is no need to add it here.

2024-11-25 14:21 UTC, qdeslandes commented on CMakeLists.txt
> +endif()
`ARGP_LIBRARY` is `REQUIRED` above, if not found, CMake will fail the generation and print an error message, no need for this condition.

2024-11-25 14:21 UTC, qdeslandes commented on CMakeLists.txt
> +endif()
All those `find_program` should be located in `docs/CMakeLists.txt`.

2024-11-25 14:21 UTC, qdeslandes commented on src/core/helper.h
> +#define bf_strerror(v) strerror(abs(v))
Why this change?

2024-11-25 14:21 UTC, qdeslandes commented on CMakeLists.txt
> +    find_program(CLANG_FORMAT_BIN NAMES clang-format-18 clang-format REQUIRED)
Those two binaries are not part of the documentation generation, but the testing logic.

2024-11-25 14:21 UTC, qdeslandes commented on CMakeLists.txt
> +endif()
Move this to `tests/bpf/CMakeLists.txt`, where `bpftool` is actually used. It's not ideal, but better than the current situation and probably sufficient for your use case.

2024-11-25 14:26 UTC, qdeslandes commented
Thanks for the PR @liudf0716 ! I've recently modified the benchmarking configuration similarly to this PR, see #174 for a example of what I'm looking for. Long story short:
- Dependencies of specific parts of the projects (e.g. doc, tests) should be discovered within the related `CMakeLists.txt`.
- Options are defined in the top-level `CMakeLists.txt` to enable/disable those different parts (e.g. `-DWITH_TESTS`).
- If a specific option is defined, the related directory should be processed by CMake.
- The new option's default value should be set to maintain the current behaviour (e.g. `WITH_TESTS` should default to `ON` as tests are always enabled at the moment).

2024-11-25 17:15 UTC, qdeslandes requested changes
Updating status

2025-01-21 09:46 UTC, qdeslandes commented
@liudf0716 Gentle ping! :)

2025-01-23 01:36 UTC, apt-install-coffee commented on src/core/helper.h
> +#define bf_strerror(v) strerror(abs(v))
strerrordesc_np is glibc specific, OpenWrt builds targeting musl or uClibc will not build with it.

2025-03-19 14:01 UTC, qdeslandes commented
@liudf0716 Any update on this? This change and the main branch diverged since Jan 21st. I will close this within a couple of weeks if it's abandoned. Thanks.

2025-03-21 00:57 UTC, liudf0716 commented
> @liudf0716 Any update on this? This change and the main branch diverged since Jan 21st. I will close this within a couple of weeks if it's abandoned. Thanks.

I’m really sorry for not having the time to address this recently—things have been incredibly busy on my end.
To answer your question, there hasn’t been any update on this since the main branch diverged on January 21st. I appreciate you checking in, and I’ll make sure to close it within the next couple of weeks if it’s no longer needed. Thanks for your patience!

2025-03-21 09:08 UTC, qdeslandes commented
> > @liudf0716 Any update on this? This change and the main branch diverged since Jan 21st. I will close this within a couple of weeks if it's abandoned. Thanks.
> 
> I’m really sorry for not having the time to address this recently—things have been incredibly busy on my end. To answer your question, there hasn’t been any update on this since the main branch diverged on January 21st. I appreciate you checking in, and I’ll make sure to close it within the next couple of weeks if it’s no longer needed. Thanks for your patience!

That's alright! I thought this PR was abandoned, but apparently it's not, disregard my comment then. I can't blame you for being busy, take the time you need :)

2026-01-14 13:31 UTC, qdeslandes commented
This PR diverged a lot from the main branch since it was opened. I'll close it, feel free to open a new one if you have an updated version of it :)

2026-01-14 13:31 UTC, closed without merging