bpfilter: add in "Quick Start" guide within the "Usage" page
facebook/bpfilter pull request #177
Opened 2024-12-15 23:30 UTC by ryanbsull

2024-12-17 12:42 UTC, qdeslandes requested changes

2024-12-17 12:42 UTC, qdeslandes commented on doc/usage/index.rst
> +	> sudo ./build/output/bpfilter -t -v debug --no-iptables
Use long options here, it's easier to understand for people learning about `bpfilter`.

2024-12-17 12:42 UTC, qdeslandes commented on doc/usage/index.rst
> +	> cd path/to/bpfilter/
`path/to/bpfilter/` -> `path/to/bpfilter/repo`

2024-12-17 12:42 UTC, qdeslandes commented on doc/usage/index.rst
> +Now let's try changing the filter from ``{192.168.1.1} ACCEPT`` to ``DENY``
`DENY` -> `DROP`

2024-12-17 12:42 UTC, qdeslandes commented on doc/usage/index.rst
> +Congratulations you have now officially used ``bpfilter`` to systematically filter out your own packets. For documentation for more complex filtering options please check under the ``DEVELOPERS`` lin
"``DEVELOPERS`` link`" -> "``DEVELOPERS`` section"

2024-12-17 12:42 UTC, qdeslandes commented on doc/usage/index.rst
> +You should now observe a change in the behavior of ``ping``
"behavior of ``ping``" -> "behavior of ``ping``."

2024-12-17 12:42 UTC, qdeslandes commented on doc/usage/index.rst
> +While the ``bpfilter`` daemon runs, now we will open up a separate window to use ``bfcli``
It would be worth mentioning `bfcli` is one of the way to use `bpfilter` (with `iptables` and `nftables`).

2024-12-17 12:42 UTC, qdeslandes commented on doc/usage/index.rst
> +The above program is just to make sure that ``bfcli`` is able to communicate with ``bpfilter``, when you run the commands you should see output from ``bpfilter`` registering that a filter has been lo
Detail what the command is doing: "The above command will...", also for a quick example, I would avoid using a set (`{...}`) and use a single address instead (`ip4.saddr eq 192.168.1.1`).

2024-12-18 17:39 UTC, ryanbsull commented
@qdeslandes let me know if the additions are acceptable or if more detail is needed

2024-12-18 20:14 UTC, qdeslandes requested changes

2024-12-18 20:14 UTC, qdeslandes commented on doc/usage/index.rst
> +	This is only to be used as an example and a more interactive test to familiarize you with ``bpfilter``, more in-depth information can be found throughout the docs.
"throughout the docs" -> "throughout the documentation"

2024-12-18 20:14 UTC, qdeslandes commented on doc/usage/index.rst
> +	> cd path/to/bpfilter/repo/
This path should be the same for all the examples. It might be simpler to remove the `cd` command from the code blocks and mention something along the lines of "we assume the following commands are run from the `bpfilter` source directory".

2024-12-18 20:14 UTC, qdeslandes commented on doc/usage/index.rst
> +The above command is just to make sure that ``bfcli`` is able to communicate with ``bpfilter``, but it's still worth working through it. This command is telling ``bpfilter`` to check incoming traffic
This part is confusing and inaccurate:
- "``bpfilter`` to check incoming traffic": it sends a request to `bpfilter` to create a new filter. `bpfilter` itself doesn't process the traffic
- "accept those connections": "connections" when it comes to packet filtering have a very specific meaning (e.g. TCP connection), `bpfilter`'s programs works at the packet level
- "asks ``bpfilter`` to check": `bpfilter` won't check anything but generate a program that does
- "``192.168.1.1`` (yourself)": that is very specific to one's network.

I would prefer something simpler and more straightforward such as:

The command above will send a request to the `bpfilter` daemon to create a chain and attach it to the `BF_HOOK_NF_LOCAL_IN` hook, located after the packet has been routed in the kernel network stack. A single rule is defined, which will accept the packet if its source IPv4 address is `192.168.1.1`. If the rule doesn't match the packet, the chain's policy is applied and the packet is accepted. In its current shape, the chain will always accept incoming packets.

2024-12-18 20:14 UTC, qdeslandes commented on doc/usage/index.rst
> +	4 packets transmitted, 0 packets received, 100.0% packet loss
We define a rule to block a specific IP and the ping fails, but does this do what you expect it to do? The command above creates a filter for `BF_HOOK_LOCAL_IN`, i.e. an input hook, meaning packets *coming* to the local host with the source IP `192.168.1.1` are accepted. It won't block packets going *out* of the local host, but the answer coming back from `192.168.1.1`.

2024-12-18 20:14 UTC, qdeslandes commented on doc/usage/index.rst
> +Congratulations you have now officially used ``bpfilter`` to systematically filter out your own packets. For documentation for more complex filtering options please check under the ``DEVELOPERS`` sec
> systematically filter out your own packets

We only filter packets coming from `192.168.1.1`.

2024-12-19 13:08 UTC, qdeslandes reviewed
Almost there, one last nit. Also, please fix the command regarding the usage of the long options in the examples.

2024-12-19 13:08 UTC, qdeslandes commented on doc/usage/index.rst
> +The command above will send a request to the bpfilter daemon to create a chain and attach it to the BF_HOOK_NF_LOCAL_IN hook, located after the packet has been routed in the kernel network stack. A s
Use double backticks around BF_HOOK_NF_LOCAL_IN and the IP address.

2024-12-30 15:39 UTC, ryanbsull commented
Hey, @qdeslandes just wanted to ping regarding this

2024-12-31 11:13 UTC, qdeslandes requested changes

2024-12-31 11:13 UTC, qdeslandes commented on doc/usage/index.rst
> +
Remove extra new line.

2024-12-31 11:13 UTC, qdeslandes commented on doc/usage/index.rst
> +	> cd path/to/bpfilter/
No need for this as we explain the commands must be run from the source dir.

2025-01-01 13:36 UTC, qdeslandes approved these changes

2025-01-01 13:36 UTC, merged

2025-01-01 13:37 UTC, qdeslandes commented
Hi @ryanbsull ,

Non-code changes are usually not the most straightforward for some reason, thanks for pushing through, I appreciate your contribution. This change is now merged!

2025-01-01 16:53 UTC, ryanbsull commented
Thanks!